apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netchecks.fullname" . }}
  labels: {{ include "netchecks.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "probe": {
        "image": {
          "pullPolicy":{{ .Values.probeConfig.image.pullPolicy | quote }},
          "repository":{{ .Values.probeConfig.image.repository | quote }},
          "tag":{{ .Values.probeConfig.image.tag | default .Chart.AppVersion | quote }}
        },
        {{- if .Values.probeConfig.resources }}
        "resources": {{ .Values.probeConfig.resources | toJson }},
        {{- end }}
        {{- if .Values.probeConfig.tolerations }}
        "tolerations": {{ .Values.probeConfig.tolerations| toJson }},
        {{- end }}
        {{- if .Values.probeConfig.affinity }}
        "affinity": {{ .Values.probeConfig.affinity | toJson }},
        {{- end }}        
        "imagePullSecrets": {{ .Values.probeConfig.imagePullSecrets | toJson }},
        "podAnnotations": {{ .Values.probeConfig.podAnnotations | toJson }}
        }
    }
