apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netchecks.fullname" . }}
  labels: {{ include "netchecks.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "probe": {
        "image": {
          "pullPolicy":{{ .Values.probeConfig.image.pullPolicy | quote }},
          "repository":{{ .Values.probeConfig.image.repository | quote }},
          "tag":{{ .Values.probeConfig.image.tag | default .Chart.AppVersion | quote }}
        },
        "imagePullSecrets": {{ .Values.probeConfig.imagePullSecrets | toJson }},
        "podAnnotations": {{ .Values.probeConfig.podAnnotations | toJson }},
        "resources": {{ .Values.probeConfig.resources | toJson }}
        }
    }
