apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netchecks.fullname" . }}
  labels:
    {{- include "netchecks.labels" . | nindent 4 }}
spec:
  # Please note that only one replica is required for the operator
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "netchecks.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.operator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netchecks.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netchecks.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.operator.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          env:
            - name: JSON_CONFIG
              value: /var/config/config.json
          volumeMounts:
            - mountPath: /var/config
              name: config-file
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-file
          configMap:
            name: {{ include "netchecks.fullname" . }}
