name: Linting

on: [push]

jobs:
  check-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1
        with:
          filter_mode: file
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
      - uses: chartboost/ruff-action@v1

  check-versions:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v4
       with:
         python-version: '3.11'
     - run: |
         python -m pip install pyyaml
         python ./scripts/check_versions.py
