name: Linting

on: [push]

jobs:
  check-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1
        with:
          filter_mode: file
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          recursive: true
          no-fail: 'true'
      - uses: chartboost/ruff-action@v1

  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - run: |
          uv run --with pyyaml ./scripts/check_versions.py

  typocheck:
    name: Spellcheck with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@master
        with:
          config: ./.typos.toml
