apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
data:
  foo: "bar"
---
apiVersion: netchecks.io/v1
kind: NetworkAssertion
metadata:
  name: k8s-config-check
  namespace: default
  annotations:
    description: Assert probe can access configmap data
spec:
  context:
    - name: somecontext
      configMap:
        name: some-config-map
  schedule: "*/5 * * * *"
  rules:
    - name: validate-configmap-value
      type: internal
      validate:
        message: Configmap should have particular value
        pattern: "somecontext.foo == 'bar'"
